version: "3.8"

services:
  mongo:
    image: mongo
    container_name: game_db
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

  backend:
    build: ./backend
    container_name: game_api
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://mongo:27017/gamedata
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

volumes:
  db-data:
